### ISSUE TITLE
Unity benötigt Lizenzinformationen / Anmeldedaten, in Docker nicht (auf Anhieb) möglich

### ISSUE THREAD

**Issue by DarkMuesli** [MarcoReitano/AvSS17#2]
Um in Unity zu arbeiten, werden beim Start Anmeldeinformationen zu einem lizenzierten Account benötigt.
Ist im Dockercontainer nicht auf Anhieb mit den offensichtlichen Mitteln möglich. Startup per Kommandozeile funktioniert nicht, muss recherchiert werden.

Im Zweifel muss eine Alternative zu Docker gefunden werden.

**Comment by schwedenmut** [comment]
https://docs.unity3d.com/Manual/CommandLineArguments.html

**Comment by schwedenmut** [comment]
Durch Bauen der Szene ohne Editor nicht mehr ein Problem.
