### ISSUE TITLE
Skripte für dei Verwaltung von Docker Benutzer unabhängig machen

### ISSUE THREAD

**Issue by schwedenmut** [MarcoReitano/AvSS17#25]
Wollte am Wochenende einem Externen das Projekt zeigen. 
Leider war dies nicht möglich und hat recht viele Fehler geschmissen.  
Hier könnte man sowohl die Verteilung der SSH Keys für einen Nutzer automatisieren, um die dauernde Passwort anfrage zu unterbinden.
Zudem scheint es zu Problemen bzgl. der Erstellung der Docker-machines durch andere User zu kommen?!?

**Comment by DarkMuesli** [comment]
Ist (bestimmt) gelöst
