### ISSUE TITLE
SimpleClient mit Generierung zusammenführen

### ISSUE THREAD

**Issue by DennisBuderus** [MarcoReitano/AvSS17#5]
@schwedenmut können uns ja mal zusammensetzen und schauen, wie wir das zusammenbekommen.

**Comment by schwedenmut** [comment]
Generierung anstoßen durch den SimpleClient wenn eine Jobmessage erhalten wurde.
Message Aknowledgen wenn Job abgeschlossen und Daten übertragen.

**Comment by DennisBuderus** [comment]
Alle Clients warten auf die Job-Queue und arbeiten die Jobs ab. 
Über die Job-Message kann festgelegt werden, welches Serialisierungsverfahren verwendet werden soll (wird auch in der Reply-Message wieder mitgegeben, damit der Master weiß, wie Serialisiert wurde). Die Serialisierte Szene wird an die in der Job-Message angegebene Reply-Queue gesendet und danach die Job-Message Aknowledged.
Der Master holt sich die Ergebnisse aus der Reply-Queue, Deserialisiert und rekonstruiert die Szene.
