### ISSUE TITLE
SRTMDataCells evtl. in gemeinsames Filesystem vom Server downloaden lassen

### ISSUE THREAD

**Issue by DennisBuderus** [MarcoReitano/AvSS17#7]
Es wäre sinnvoll die SRTM Dateien vom Server herunterladen zu lassen, damit nicht jeder Client die gleiche Datei herunterladen muss.

**Comment by schwedenmut** [comment]
Aktuelles Problem, dass  SRTMDataCells.cs Zeile 490 ff. nicht wirklich greifen.

**Comment by schwedenmut** [comment]
Aktuell werden die SRTM Daten - zumindest unter macOS - an einem suboptimalen Speicherort persistiert.  
<img width="1575" alt="bildschirmfoto 2017-09-28 um 15 49 10" src="https://user-images.githubusercontent.com/9077622/30970213-d6d689cc-a464-11e7-8aaf-c82ac5ada4c4.png">
Man beachte den Pfadnamen XD

**Comment by DennisBuderus** [comment]
Das ist der Pfad, der noch von mir in den projectsettings zuletzt verwendet wurde... Der ist nicht wirklich hard-coded irgendwo drin... Dafür hatten wir ja diese Meldung vorher drin, dass der osm und srtm path gesetzt werden muss... Hab das quasi nur mitgepusht... 


Gesendet von VMware Boxer


Am 28.09.2017 15:52 schrieb schwedenmut <notifications@github.com>:

Aktuell werden die SRTM Daten - zumindest unter macOS - an einem suboptimalen Speicherort persistiert.
 
Man beachte den Pfadnamen XD

**Comment by schwedenmut** [comment]
> Der ist nicht wirklich hard-coded irgendwo drin

https://github.com/MarcoReitano/AvSS17/blob/a3312528585bf471116e3dd001fd591c91a65590/AVSUnity/Assets/SRTM/SRTMHeightProvider.cs#L51
und wird dann mit weiteren Daten erweitert:
https://github.com/MarcoReitano/AvSS17/blob/a3312528585bf471116e3dd001fd591c91a65590/AVSUnity/Assets/SRTM/SRTMDataCell.cs#L48

Somit ist der Path doch hard-coded drin, oder nicht @DennisBuderus ?!?

**Comment by DennisBuderus** [comment]
Hola... Wie ich gestern schon geschrieben habe: den Pfad soll man eigentlich über das config-editorwindow setzen, damit er in den editorprefs gesetzt wird.. Die "hard-coded" Initialisierung kann auch weggelassen werden, dann wird darauf hingewiesen, dass der Pfad nicht gesetzt ist. Ist quasi nur ein fallback während der Entwicklung gewesen, damit der auf jeden Fall gesetzt ist... Eigentlich sollte jeder den aber für sich konfigurieren... Hätten wir den fallback weggelassen, würde es solange nicht wirklich funktionieren bis du ihn selbst setzt... So hab ichs zumindest gerade in Erinnerung.. 


VG Dennis 


Gesendet von VMware Boxer


Am 29.09.2017 16:56 schrieb schwedenmut <notifications@github.com>:

Der ist nicht wirklich hard-coded irgendwo drin

https://github.com/MarcoReitano/AvSS17/blob/a3312528585bf471116e3dd001fd591c91a65590/AVSUnity/Assets/SRTM/SRTMHeightProvider.cs#L51
und wird dann mit weiteren Daten erweitert:
https://github.com/MarcoReitano/AvSS17/blob/a3312528585bf471116e3dd001fd591c91a65590/AVSUnity/Assets/SRTM/SRTMDataCell.cs#L48

Somit ist der Path doch hard-coded drin, oder nicht @DennisBuderus ?!?

**Comment by schwedenmut** [comment]
Hmmm, macht halt nur wenig Sinn bei Workern ein GUI Fenster zu öffnen, wo man dann einen bzw. mehrere Speicherpfade hinterlegen muss.

**Comment by schwedenmut** [comment]
https://thenewstack.io/methods-dealing-container-storage/

**Comment by DarkMuesli** [comment]
Info:
Die Größen der SRTM-Datenpakete bewegen sich vom einstelligen KB bis zum (niedrigen) einstelligen MB Bereich. (Ich habe bei Stichproben nichts > 1,5 MB gesehen). Im worst-case also das vierfache davon, wenn ein Tile genau im Schnittpunkt liegt.
Zum Vergleich: Eine serialisierte Szene bewegt sich (je nach Serialisierung und Tilegröße) im ein- bis dreistelligen MB Bereich.
Die SRTM-Daten kommen zwar im Gegensatz dazu von außen, aber aufgrund unserer extrem guten Internetanbindung gibt es keine dringende Notwendigkeit für ein gemeinsames Filesystem.

**Comment by DarkMuesli** [comment]
Nicht notwendig - Evtl. für zukünftige Releases interessant.
